### ISSUE TITLE
Toys Guix Channel Search

### ISSUE THREAD

**Issue by jgarte** [TinHead/th-guix-channel#1]
Hi fellow Guixer,

Would you be interested in joining our Guix channel search engine?

https://toys.whereis.みんな/

If so, send a patch here adding your channel:

https://git.sr.ht/~whereiseveryone/toys#join

**Comment by TinHead** [comment]
Hey thanks I wasn't aware of it I'll send a patch when I get to it

**Comment by TinHead** [comment]
Request was sent. Cheers!
